"""
significance_test.py
-----------------------
Tests whether the Dual-Stream model's CV performance is statistically
significantly different from each baseline, using paired tests across the
same 5 CV folds (same fold splits were used for every model, so pairing
by fold index is valid).

Reports both:
    - Wilcoxon signed-rank test (non-parametric, doesn't assume normality --
      the standard choice in this literature, though note the caveat below)
    - Paired t-test (parametric, reported alongside for completeness)

IMPORTANT CAVEAT (report this honestly in the paper):
    With only 5 folds, statistical power is inherently low. The smallest
    possible two-sided Wilcoxon p-value with n=5 is ~0.0625, so it can
    never reach the conventional p<0.05 threshold even if the Dual-Stream
    model wins every single fold. Report exact p-values and effect sizes
    (mean difference) rather than only a significant/not-significant
    verdict, and treat this as supporting evidence alongside the test-set
    result, not as a standalone significance claim.

Requires results_log.json to have been generated by the UPDATED model.py
and baseline_comparison.py (which now save raw per-fold scores under
"cv_folds"). If your results_log.json predates this, re-run:
    python preprocess_datasets.py
    python model.py
    python baseline_comparison.py
before running this script.

Run from PowerShell:
    cd "D:\MITS\08-09-26\Dataset"
    pip install scipy
    python significance_test.py

Output:
    tables_output/table7_statistical_significance.csv
"""

import os
import json
import csv
import numpy as np
from scipy import stats

RESULTS_LOG = "results_log.json"
OUTPUT_DIR = "tables_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

DUAL_STREAM_LABEL = "Taiwan - Dual-Stream (Temporal GRU+Attention + Static + Gated Fusion)"
COMPARISON_MODELS = [
    ("Ablation (No Temporal)", "Taiwan - Ablation (Flattened features, no temporal structure)"),
    ("Logistic Regression", "Taiwan - Baseline: LogisticRegression"),
    ("Random Forest", "Taiwan - Baseline: RandomForest"),
    ("XGBoost", "Taiwan - Baseline: XGBoost"),
    ("SVM (RBF)", "Taiwan - Baseline: SVM_RBF"),
]
METRIC = "auc"  # the metric folds are compared on


def load_latest_by_label():
    with open(RESULTS_LOG, "r") as f:
        results = json.load(f)
    latest = {}
    for entry in results:
        latest[entry["label"]] = entry
    return latest


def get_fold_values(entry, metric=METRIC):
    if "cv_folds" not in entry or not entry["cv_folds"]:
        return None
    return np.array([f[metric] for f in entry["cv_folds"]])


if __name__ == "__main__":
    if not os.path.exists(RESULTS_LOG):
        print(f"[!] {RESULTS_LOG} not found.")
        exit(1)

    latest = load_latest_by_label()

    if DUAL_STREAM_LABEL not in latest:
        print(f"[!] Dual-Stream results not found in {RESULTS_LOG}.")
        exit(1)

    ds_entry = latest[DUAL_STREAM_LABEL]
    ds_folds = get_fold_values(ds_entry)
    if ds_folds is None:
        print("[!] Dual-Stream entry has no 'cv_folds' data. Your results_log.json")
        print("    predates the per-fold logging fix. Re-run model.py to regenerate it.")
        exit(1)

    print("=" * 90)
    print(f"  STATISTICAL SIGNIFICANCE TEST (metric: {METRIC.upper()}, paired across 5 CV folds)")
    print("=" * 90)
    print(f"  Dual-Stream fold {METRIC}s: {np.round(ds_folds, 4).tolist()}")
    print(f"  Dual-Stream mean: {ds_folds.mean():.4f}\n")

    rows = []
    header = ["Comparison", "DualStream_mean", "Other_mean", "Mean_diff",
              "Wilcoxon_stat", "Wilcoxon_p", "TTest_stat", "TTest_p", "DualStream_wins_folds"]

    for name, label in COMPARISON_MODELS:
        if label not in latest:
            print(f"  [skip] {name}: not found in {RESULTS_LOG}")
            continue
        other_folds = get_fold_values(latest[label])
        if other_folds is None:
            print(f"  [skip] {name}: no per-fold data logged (re-run to fix)")
            continue
        if len(other_folds) != len(ds_folds):
            print(f"  [skip] {name}: fold count mismatch ({len(other_folds)} vs {len(ds_folds)})")
            continue

        diff = ds_folds - other_folds
        wins = int((diff > 0).sum())

        try:
            wilcoxon_stat, wilcoxon_p = stats.wilcoxon(ds_folds, other_folds)
        except ValueError:
            wilcoxon_stat, wilcoxon_p = float("nan"), float("nan")  # all diffs zero, test undefined

        ttest_stat, ttest_p = stats.ttest_rel(ds_folds, other_folds)

        print(f"  Dual-Stream vs {name}:")
        print(f"    Mean diff: {diff.mean():+.4f}   Dual-Stream wins {wins}/{len(ds_folds)} folds")
        print(f"    Wilcoxon p={wilcoxon_p:.4f}   Paired t-test p={ttest_p:.4f}")
        print()

        rows.append([
            f"Dual-Stream vs {name}",
            f"{ds_folds.mean():.4f}", f"{other_folds.mean():.4f}", f"{diff.mean():+.4f}",
            f"{wilcoxon_stat:.4f}" if not np.isnan(wilcoxon_stat) else "n/a",
            f"{wilcoxon_p:.4f}" if not np.isnan(wilcoxon_p) else "n/a",
            f"{ttest_stat:.4f}", f"{ttest_p:.4f}",
            f"{wins}/{len(ds_folds)}",
        ])

    out_path = os.path.join(OUTPUT_DIR, "table7_statistical_significance.csv")
    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)
    print(f"[Saved] {out_path}")

    print("\n" + "=" * 90)
    print("  CAVEAT: with n=5 folds, the smallest possible two-sided Wilcoxon p-value")
    print("  is ~0.0625 -- it cannot reach p<0.05 even with a perfect 5/5 sweep. Report")
    print("  exact p-values and fold-win-counts as supporting evidence, not a standalone")
    print("  significance claim. This is standard practice for 5-fold CV comparisons.")
    print("=" * 90)
